runtimes/erlang-R16B02.conf
=> Checksum in erlang-R16B02.conf is fixed

runtimes/node-4.2.1.conf
Change the link and you are good to go. 
@variadico @johnSchnake
=> Added node-v4.2.1 into the runtimes

README.md
Forgot to update the readme. 
@variadico
=> Added node-4.2.1 to the README

runtimes/php-apache-5.5.15-apc2.conf, runtimes/php-fpm-nginx-5.5.15-apc2.conf
Added compilation directive to include opcache, then added some small fixes to php.ini so it is included.
@tcahill @philpennock @krobertson
=> Speed up php packages by including opcache

runtimes/php-apache-5.5.15-apc3.conf, runtimes/php-fpm-nginx-5.5.15-apc3.conf
=> Added pecl support and install memcache and uploadprogress by default

packages/imagemagick-6.8.9-6-apc2.conf, runtimes/php-5.4.31-apc3.conf, runtimes/php-apache-5.5.15-apc5.conf, runtimes/php-fpm-nginx-5.5.15-apc4.conf
=> Updated libpng to 1.6.19

packages/postgres-9.4.5.conf
This adds Postgres 9.4.5 and also includes the start script for NFS persistence.
@zquestz
=> Add Postgres 9.4.5

packages/postgres-9.4.4-apc1.conf
=> Rename Postgres package script

packages/iperf-2.0.5.conf
Iperf is a network testing tool that can be used to generate data
streams and measure the throughput of the underlying network.
Please review @zquestz
=> Add Iperf 2.0.5

README.md, os/ubuntu-14.04.3-build-essential.conf, os/ubuntu-14.04.3.conf
*Added the conf files for ubuntu-14.04.3
*Updated the README based on new packages
@variadico @earlruby
=> Added ubuntu 14.4.3

packages/gnatsd-0.7.2.conf
This adds gnatsd version 0.7.2.
@wallyqs @yaso195 @zquestz
=> Add gnatsd package

legacy/packages/apache-tomcat-7.0.47.conf, legacy/packages/apache-tomcat-7.0.55.conf
This change fixes ENGT-5178.
@variadico
=> Changed the folder permissions for old tomcat packages

runtimes/go-1.6.conf
This adds Go 1.6.
@yaso195 @zquestz
=> Add Go 1.6

packages/apache-tomcat-8.0.30.conf
Fixes issue reported by QC here -> https://apcera.atlassian.net/browse/ENGT-7100?filter=-1
@tw4dl @variadico
=> Fix JSP issue with Tomcat 8.0.30

README.md, packages/apache-2.4.18.conf, packages/apache-tomcat-8.0.33.conf, packages/git-2.8.0.conf, packages/postgres-9.4.7.conf, packages/redis-2.8.24.conf, packages/rsync-3.1.2.conf, packages/subversion-1.9.3.conf, runtimes/erlang-otp-18.3.conf, runtimes/go-1.5.3.conf, runtimes/node-4.4.2.conf, runtimes/perl-5.22.1.conf, runtimes/python-2.7.11.conf, runtimes/python-3.5.1.conf, runtimes/ruby-2.2.4.conf, runtimes/ruby-2.3.0.conf
=> Update versions for node perl python ruby apache subversion git postgres erlang

buildpkg.sh, runtimes/node-5.10.0.conf, runtimes/php-5.5.33.conf, runtimes/php-5.6.19.conf
[x] update url to our s3 buckets
[x] remove mv mirror to gz statements after the s3 url update
relates to https://github.com/apcera/packages/pull/5
@variadico @zquestz
=> add node-5.10.0, php-5.5.33, and php-5.6.19

buildpkg.sh, packages/mysql-5.6.25-apc3.conf, runtimes/node-5.10.0-apc1.conf
add mysql-5.6.25-apc3 with perl-5 dependency
update node-5.10.0 with node-5 provider capability
=> add mysql-5.6.25-apc3 and update node-5.10.0

packages/s3cmd-1.6.1.conf
This package is require to create apps to test our s3 gateway.
@variadico @earlruby @zquestz
=> Added s3cmd to the packages

runtimes/node-5.10.1.conf
Security update for node-5.10.0 https://nodejs.org/en/blog/release/v5.10.1/
=> Node 5.10.1

packages/bzr-2.6.0.conf
Earlier, it was not being installed properly. Any app that has been created
from this package were not having the bzr package. Now, it is fixed.
@zquestz @variadico
=> Fixed bzr-2.6.0 package

runtimes/node-4.4.4.conf, runtimes/node-5.11.1.conf, runtimes/node-6.1.0.conf
This adds:
* Node 5.11.1
* Node 4.4.4
* Node 6.1.0
@tw4dl @y0ssar1an @yaso195
=> Update Node packages

runtimes/go-1.5.4.conf
=> Add Go 1.5.4

runtimes/openjdk-1.8.0-u60-b23.conf
=> Add OpenJDK 8

runtimes/node-4.4.5.conf
=> Add Node 4.4.5

packages/mysql-5.6.31.conf, packages/postgres-9.4.8.conf, packages/postgres-9.5.3.conf
@tw4dl @y0ssar1an @yaso195 @zquestz
=> Add new MySQL and Postgres

runtimes/node-6.2.1.conf
@yaso195 @tw4dl @zquestz @y0ssar1an
=> Add Node 6.2.1

runtimes/go-1.6.2.conf
@yaso195 @zquestz @tw4dl @y0ssar1an
=> Add Go 1.6.2

packages/rabbitmq-3.5.5-apc2.conf
Fix persistence in RabbitMQ.
Fixes #ENGT-7591
=> Fix persistence in RabbitMQ

runtimes/node-4.4.6.conf, runtimes/node-5.12.0.conf
Update Node to latest security release.
https://nodejs.org/en/blog/vulnerability/june-2016-security-releases/
@lilirui @lloydde @tw4dl @vitroth @yaso195 @zquestz
=> Add Node 4.4.6 and 5.12.0

packages/rsnapshot-1.4.2.conf
This adds the rsnapshot package. It has scripts to download, compile and install rsnapshot
Fixes #ENGT-6930
@earlruby, @bwerthmann, @variadico
=> Addition of package rsnapshot.

runtimes/go-1.6.3.conf
This adds Go 1.6.3.
@lloydde @tw4dl @yaso195 @zquestz
=> Add Go 1.6.3

packages/apache-2.2.31.conf, packages/apache-2.4.23.conf, packages/nginx-1.11.3.conf, runtimes/php-5.6.24.conf
This adds:
* Apache 2.2.31
* Apache 2.4.23
* PHP 5.6.24
* Nginx 1.11.3
@bwerthmann @GeoffDNeal @lloydde @yaso195 @zquestz
=> Update Apache, Nginx, and PHP

packages/nginx-1.11.1.conf, packages/nginx-1.11.3.conf
* Added env var NGINX_ROOT so that apps using this package can find NGINX.
* Added -apc1 to the package name so that the new package doesn't break dependencies.
@zquestz @variadico @yaso195 @y0ssar1an
=> Added path to NGINX

runtimes/php-apache-5.6.24.conf, runtimes/php-fpm-nginx-5.6.24.conf
Adds the following packages:
* php-apache-5.6.24
* php-fpm-nginx-5.6.24
@GeoffDNeal @lilirui @lloydde @zquestz
=> Add new PHP server packages

packages/minio-client-2016-08-21.conf
Just the minio client package. Will be useful for customers as well as the test suite. The package is also tiny.
@earlruby @variadico @bwerthmann @yaso195
=> Added minio client package script.

runtimes/php-5.4.31-apc4.conf, runtimes/php-5.5.33-apc1.conf, runtimes/php-5.6.24-apc1.conf, runtimes/php-apache-5.5.15-apc7.conf, runtimes/php-apache-5.6.24-apc1.conf, runtimes/php-fpm-nginx-5.5.15-apc5.conf, runtimes/php-fpm-nginx-5.6.24-apc1.conf
Updates all latest package releases to libpng 1.6.26. 
@earlruby @variadico @lilirui
=> Update currently supported packages to libpng 1.6.26

runtimes/ruby-1.8.7-p374-apc1.conf, runtimes/ruby-1.9.3-p547-apc1.conf, runtimes/ruby-2.0.0-p643-apc1.conf, runtimes/ruby-2.1.5-apc2.conf, runtimes/ruby-2.2.3-apc1.conf, runtimes/ruby-2.2.4-apc1.conf, runtimes/ruby-2.3.0-apc1.conf
Update all the ruby packages to use bundler-1.11.2.
Fixes #ENGT-9446
@variadico @zquestz @earlruby
=> Upgrade bundler to latest version

packages/minio-2016-10-24.conf, packages/minio-client-2016-10-07.conf
Added the following updated minio packages:
https://s3.amazonaws.com/apcera-sources/minio/minio-2016-10-24.tar.gz
https://s3.amazonaws.com/apcera-sources/minio/minio-client-2016-10-07.tar.gz
@variadico
=> Update Minio packages to the latest version.

packages/couchdb-2.0.0.conf, packages/mongodb-3.2.10.conf
=> Added couchdb and mongodb packages

packages/s3cmd-1.6.1-apc2.conf
Refactors s3cmd script. Also, adds `s3cmd-1.6.1-apc2` provides and fixes Python installation.
=> Refactor s3cmd script

packages/mysql-5.6.35.conf, packages/mysql-client-5.6.35.conf
Just updates the current MySQL packages to 5.6.35.
@earlruby @variadico @shr3kst3r
=> Added package script for mysql 5.6.35 client and server

README.md, packages/bonnie++.conf
=> Added bonnie++ package for disk IO testing

packages/mongodb-3.5.10.conf
Leaving the old package as is and adding a new version. Already uploaded tgz file to S3 and building the package on kiso cluster was successful
Package export was also successful
Running on Kiso cluster
Test application running on Kiso cluster
Connecting to DB and adding elements also works
=> Mongo packaging fixes and upgrade

runtimes/go-1.8.3.conf
=> Adding go-1.8.3
