- README.md
If people `apc package build` multiple versions of a runtime without `--name`, they will end up overwriting the previous build. If they only build one version, they will wonder why `go-1.5.1` didn't appear in `package list -ns /`.
@zquestz
> Add name flag to package build example

- runtimes/php-5.4.31-apc2.conf
- runtimes/php-apache-5.5.15-apc4.conf
Currently QC has Apache 2.4 packages and can't use them due to an artificial limitation in our current scripts. This just allows any apache to be used, not just 2.2.
@schancel @philpennock @tw4dl
> Allow any apache to be used for php, not just 2.2

- os/ubuntu-13.10-apc1.conf
- os/ubuntu-14.04-apc1.conf
Added cron to the base ubuntu 14.04 image.
Since I was here I also re-enabled the /home/runner home dir, as the ruby stager requires it for git based dependencies.
@schancel @tw4dl @lilirui @mbhinder
> Add cron to base OS package

- .gitignore
- packages/postgres-9.4.4.conf
Currently, NFS persistence isn't supported for Postgres. When a user
mounts an NFS volume under Postgres' data directory, it causes the
database to fail. This adds a start script that a user could use to
reinitialize the database data directory if needed for persistence.
Resolves ENGT-4156
@zquestz
> Add Postgres start script

- packages/mysql-5.6.25-apc1.conf
This adds support for NFS backed MySQL databases.
NFSv4 is *required* for this to work.
@earlruby @zquestz @yaso195
> Add NFS persistence to MySQL 5.6.25

- legacy/runtimes/go-1.1.1.conf
- legacy/runtimes/go-1.1.2.conf
- runtimes/go-1.2.conf
- runtimes/go-1.3.conf
- runtimes/go-1.4.conf
- runtimes/go-1.5.1.conf
Our fork of apcera/godep is so old that the code.google.com is no longer up. I tried building the package with the official godep tool and everything worked fine. Is there any reason not to use the official godep repo? It seems like most people would be using the official version locally anyway.
Resolves [ENGT-5884](https://apcera.atlassian.net/browse/ENGT-5884)
@zquestz
> Use official godep

- legacy/packages/mysql-5.6.25-apc1.conf
- packages/mysql-5.6.25-apc2.conf
This updates the dependency of Perl package from 5.20 only to any 5.x.
@variadico @tw4dl @zquestz
> Unlock the perl version from 5.20

- packages/mysql-5.6.25-apc4.conf
Shebang for mysql_install_db is now `#!/usr/bin/env perl` so that it can pickup any resolved perl, instead of a hard coded one.
@tw4dl @variadico @schancel
> Added new mysql script which works with multiple versions of perl

- packages/newrelic-java-3.28.0.conf
This adds New Relic 3.28 for Java. In one of our New Relic tutorials, we make people write their own package script. Unfortunately, that needed some extra touches because of a Java `IOException`. This fixes the package script in that tutorial.
I tried to make this package generic and not hard-code keys or app names. That means, in order to use this package, you'll need to create your Java app like this.
```
apc app create my-app --depends-on package.newrelic-java-3.28.0 --set-env 'JAVA_OPTS=-Dnewrelic.config.license_key=1234 -Dnewrelic.config.app_name=my-app'
```
Fixes #[ENGT-7363](https://apcera.atlassian.net/browse/ENGT-7363)
@alextoombs @lloydde @lparis @rusher81572 @tw4dl @yaso195 @zquestz
> Add New Relic script

- packages/s3cmd-1.6.1.conf
We have to exactly specify the python version number for s3cmd package. Becausem  this package will not be installed correctly to the apps, if the app is using a different python package than the one used to build this package. 
@variadico
> Updated the python version for s3cmd package

- README.md
- Verification.md
- packages/ltp-2016.05.10.conf
* Added Linux Test Project package for fcntl file lock tests.
* locktest is a C program developed by the Bull GNU/Linux NFSv4 project.
* This test is aimed at stressing the fcntl locking functions.
A master process sets a lock on a file region (byte range locking). Several
slave processes try to perform operations on this region, such as: read,
write, set a new lock ... The expected results of these operations are known.
If the operation's result is the same as the expected one, the test succeeds,
otherwise it fails.
Lock tests stress POSIX locks.
(This PR replaces https://github.com/apcera/package-scripts/pull/92)
@bwerthmann @variadico @zquestz
> Linux Test Project package

- runtimes/mysql-client-5.6.31.conf
* Created a MySQL client package.
* Used this package in the mysql-backup sample app (in place of apt-get).
* Also updated the bash_start.sh script in mysql-backup sample app so that it returns a 503 (service unavailable) and the message "First backup has not completed" if the first backup has not yet been completed.
* Updated the docs as necessary.
Fixes #ENGT-8354
I had to update 6 repos and generate 6 PRs for this sample app.
@ketandixit @lilirui @variadico @yaso195
> Create mysql-client package to use in mysql-backup sample app

- packages/mysql-client-5.6.31.conf
Moved mysql-client-5.6.31 from runtimes to packages
Fixes #ENGT-8354
@zquestz @ketandixit @variadico
> Moved mysql-client-5.6.31 from runtimes to packages

- README.md
- packages/rsync-3.1.2-apc1.conf
Fixed rsync install path. 
* New version of the rsync package that works.
* Updated README with lists of current packages, runtimes, and os files.
@zquestz @variadico @lilirui
> Fixed rsync install path

- packages/minio-2016-09-11.conf
Adds a package script for the latest version of minio server. Docs are included at the top of the package script, and describe how to setup persistence and the logical start command to use.
Minio uses a rolling release cycle, so the package is time stamped, not versioned, as a version number is not available.
@variadico @earlruby @bwerthmann
> Add package script for minio-2016-09-11

- packages/iperf-3.0.11.conf
This adds the `iperf3` package. It's version 3.0.11 because that is the version you get when you `apt-get install iperf3` on Ubuntu 16.04, which is what our `iperf` servers are running.
`iperf3` has been completely rewritten from scratch. It may solve the `iperf` performance issues described in [ENGT-9569](https://apcera.atlassian.net/browse/ENGT-9569).
PS I don't know where the kjackson03 commit came from.
@variadico
> Add iperf3 package

- runtimes/ruby-2.2.5.conf
Since Ruby 2.2.5 was released for a while, we should have this package and maybe replace 2.2.4 in our system test.
@variadico @yaso195 @zquestz
> Add ruby v2.2.5 package

- README.md
Left this reference behind in the README after I updated ImageMagick in #144. Whoops!
> Remove reference to an old version of ImageMagick from README

- README.md
- packages/apt-mirror-0.5.3.conf
Use apt-mirror to mirror the Ubuntu repos. This is an internal package, it does not need to be a standard part of our distributed package set.
> ENGT-10684: Add apt-mirror

- packages/apache-2.4.27.conf
Includes updates to `apr` (1.6.2) and `apr-util` (1.6.0).
This is part of the resolution for [ENGT-10724](https://apcera.atlassian.net/browse/ENGT-10724).
Companion PR to [`continuum-stagers` #100](https://github.com/apcera/continuum-stagers/pull/100).
> Add apache v2.4.27 package

- os/Vagrantfile
- os/centos-7.ks
This simplifies the creation of the CentOS tarball by running the script
that creates the tarball directly on the Vagrant-managed VM rather than
creating another VM inside that one (I was unable to generate a tarball
without this option as livemedia-creator simply hung indefinitely).
> Add --no-virt to livemedia-creator options

- os/centos-7.ks
Accidentally changed the install URL in the kickstart script, which cause installation to fail.
> fix error in kickstart script
